[tool.isort]
profile = 'black'
skip_glob = '*/migrations/*.py'
skip = 'default_settings.py'

[tool.black]
line-length = 88
skip-string-normalization = true
verbose = false
diff = false
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''
force-exclude = '((.*)?default_settings.py|(.*)migrations(.*))'

[tool.ruff]
line-length = 120
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "B", # flake8-bugbear
]
src = ["oioioi"]
exclude = [
    "migrations",
    "oioioi/**/*settings.py"
]
target-version = "py311"
ignore = [
    "B904",
    "B026",
]
